tasks:
  - init: composer install
    command: composer install
  - command: cp .env.example .env
  - command: php artisan serve

ports:
  - port: 8000
    onOpen: open-browser

image:
  file: .gitpod.dockerfile
