tasks:
  - init: composer install
    command: php artisan serve
  - init: cp .env.example .env

ports:
  - port: 8000
    onOpen: open-browser

image:
  file: .gitpod.dockerfile

vscode:
  extensions:
    - MehediDracula.php-namespace-resolver@1.1.8:XkLZydiXMIueRdwf/qurhQ==